name: run push images

on:
  pull_request:
    branches: [ master ]

env:
  REGISTRY: crpi-0ecikjs9ylb2hqyo.cn-hangzhou.personal.cr.aliyuncs.com
  REPOSITORY: pixiu-public

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: publish kubernetes or custom images
        run: chmod +x ./app && ./app -v 2 --harbor ${{ env.REGISTRY }} --image-repository ${{ env.REPOSITORY }} --user ${{ secrets.HARBOR_NAME }} --password ${{ secrets.HARBOR_PASSWORD }}
