name: push kubernetes images

env:
  KubernetesVersion: 1.19.16

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install kubernetes repo
        run: sudo apt-get update &&
             sudo apt-get install -y apt-transport-https ca-certificates curl &&
             sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg &&
             echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list &&
             sudo apt-get update

      - name: install kubeadm
        run: sudo apt-get install -y kubeadm=${{ env.KubernetesVersion }}-00

      - name: publish kubernetes images
        run: chmod +x ./app && ./app -v 2 --kubernetes-version v${{ env.KubernetesVersion }}
